import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

/**
 * Contract guard for the fixer agents' prompts.
 *
 * Issue #77: over a week of one adoption, `guardrails/added-suppression` fired
 * ten times and every one was a fixer writing a `// Stryker disable` during the
 * fix loop; a separate run resolved nine of thirteen duplication findings with
 * self-authored `fallow-ignore-next-line` comments. The auditor caught all of
 * it — but catching it converts a violation the FIXER was meant to resolve into
 * a config grant only the main agent can write, which is the opposite of what
 * the loop is for. The prompt said not to suppress; it did not say what to do
 * instead. These assertions pin the positive half of that contract, because a
 * prompt has no other regression test.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const repoDirectory = path.resolve(here, '../..');
const agentsDirectory = path.join(repoDirectory, 'guardrails-plugin', 'agents');

function agentSource(name: string): string {
  return readFileSync(path.join(agentsDirectory, `${name}.md`), 'utf8');
}

/**
 * What the fast fixer's prompt has to say, and why each phrase is load-bearing.
 * The two directives are named literally because the generic word
 * "suppression" demonstrably did not cover them for the agent: every observed
 * breach wrote one of these two exact comment forms.
 */
const FAST_FIXER_CONTRACT: readonly (readonly [string, string])[] = [
  ['reports a mutant it cannot kill', 'reported, never suppressed'],
  ['names the directive those breaches actually wrote', 'Stryker disable'],
  ['reports a clone it cannot extract', 'reported, never ignored'],
  ['names the ignore-comment the clone breaches wrote', 'fallow-ignore'],
  // A prompt that forbids the suppression without naming the real escape hatch
  // leaves the agent with no modelled way out — which is how it got here.
  ['says where a real exemption lives', 'guardrails.config.json'],
  ['says who approves one', 'developer'],
];

describe('fixer agents — report-never-silence contract', () => {
  it.each(FAST_FIXER_CONTRACT)('%s', (_case, phrase) => {
    expect(agentSource('guardrail-fixer')).toContain(phrase);
  });

  it('keeps the thorough tier inheriting the contract by reference', () => {
    // One source of truth for the rules: the thorough agent restates its own
    // escalation stance but must not fork the constraint list.
    const thorough = agentSource('guardrail-fixer-thorough');
    expect(thorough).toContain('guardrail-fixer');
    expect(thorough).toContain('reported, never suppressed');
  });

  it('carries the contract into the committed Copilot fixers', () => {
    // `.github/agents/` is generated by scripts/sync-agents.mjs but COMMITTED —
    // the Copilot cloud agent reads it from the default branch, so a stale copy
    // ships the old contract to a whole surface.
    for (const name of ['guardrail-fixer', 'guardrail-fixer-thorough']) {
      const generated = readFileSync(
        path.join(repoDirectory, '.github', 'agents', `${name}.agent.md`),
        'utf8',
      );
      expect(generated, name).toContain('reported, never suppressed');
    }
  });
});

/**
 * What the fast fixer's prompt has to say about a rule whose mechanical fix
 * changes behaviour, and why.
 *
 * Issue #78, suggestion (2). Two fixers were handed the identical
 * `unicorn/no-null` finding on a nullable database column: one wrote
 * `=== undefined`, which satisfies the rule and leaves the guard unreachable
 * for the `null` it existed to catch; the other wrote a `typeof` narrowing,
 * which is green AND correct. Routing the rule to the better model (#84) does
 * not by itself name the right edit — the prompt is the only place the two
 * runs differed, so it has to carry the worked example and, more importantly,
 * the question the example exists to teach.
 */
const BEHAVIOUR_CHANGING_FIX_CONTRACT: readonly (readonly [string, string])[] =
  [
    ['names the measured rule', 'unicorn/no-null'],
    ['names the idiom that rule bans', '== null'],
    ['names the edit that broke the guard', '=== undefined'],
    ['names a shape that is green and correct', "typeof x !== 'number'"],
    // Kept to one source line: the prompts are hard-wrapped prose, so a phrase
    // that spans a wrap would pin the wrapping rather than the words.
    [
      'generalizes past the one rule',
      'which values the old expression matched',
    ],
    // The sibling rules get the question, not a second recipe: whether deleting
    // a check the type system calls unnecessary is safe depends on whether the
    // declared type is a fact or an assertion, which no recipe can decide.
    ['names the type-belief family', 'no-unnecessary-condition'],
    ['says what makes that family unsafe', 'trust boundary'],
  ];

describe('fixer agents — behaviour-changing-fix contract', () => {
  it.each(BEHAVIOUR_CHANGING_FIX_CONTRACT)('%s', (_case, phrase) => {
    expect(agentSource('guardrail-fixer')).toContain(phrase);
  });

  it('points the thorough tier at the section without forking it', () => {
    // Same one-source-of-truth rule as the constraint list: the thorough tier
    // is the one handed these findings from attempt 1, so it must NAME the
    // class — but the worked example stays in the fast tier's prompt alone.
    const thorough = agentSource('guardrail-fixer-thorough');
    expect(thorough).toContain('unicorn/no-null');
    expect(thorough).toContain('obvious fix changes behaviour');
    expect(thorough).not.toContain('=== undefined');
  });

  it('carries the worked example into the committed Copilot fixer', () => {
    const generated = readFileSync(
      path.join(repoDirectory, '.github', 'agents', 'guardrail-fixer.agent.md'),
      'utf8',
    );
    expect(generated).toContain("typeof x !== 'number'");
  });
});
