import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

/**
 * Packaging guard for the plugin's skills. A skill only earns its keep if it is
 * (a) shipped and (b) REACHABLE — an agent that never hears about it will
 * rediscover the method the expensive way. So this pins both the skill's own
 * shape and the pointer from the agent tier that routes to it.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const pluginDirectory = path.resolve(here, '../../guardrails-plugin');
const skillsDirectory = path.join(pluginDirectory, 'skills');

function skillNames(): string[] {
  return readdirSync(skillsDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

describe('guardrails-plugin skills', () => {
  it('gives every skill a SKILL.md with name and description frontmatter', () => {
    const names = skillNames();
    expect(names.length).toBeGreaterThan(0);
    for (const name of names) {
      const source = readFileSync(
        path.join(skillsDirectory, name, 'SKILL.md'),
        'utf8',
      );
      const frontmatter = source.split('---', 2)[1] ?? '';
      // The description is the trigger: it is what a runtime matches on to
      // decide whether the skill applies, so an empty one makes it unreachable.
      expect(frontmatter, name).toContain(`name: ${name}`);
      expect(frontmatter, name).toMatch(/description: \S/);
    }
  });

  it('ships the mutation skill and points the thorough fixer at it', () => {
    // `stryker/` is a loose-class prefix, so surviving mutants route to the
    // THOROUGH tier from attempt 1 — that agent is the one that needs the method.
    expect(skillNames()).toContain('crushing-mutants');
    const thorough = readFileSync(
      path.join(pluginDirectory, 'agents', 'guardrail-fixer-thorough.md'),
      'utf8',
    );
    expect(thorough).toContain('crushing-mutants');
  });

  it('emits each skill as a committed doc for surfaces without skills', () => {
    // Copilot has no skill mechanism, and its cloud agent reads from the default
    // branch — so the same content ships as a generated, COMMITTED doc.
    for (const name of skillNames()) {
      const skillDocument = readFileSync(
        path.resolve(here, `../../docs/guardrails/${name}.md`),
        'utf8',
      );
      expect(skillDocument, name).toContain(
        'Generated by scripts/sync-agents.mjs',
      );
      // Body, not just a stub: the doc must carry the method itself.
      expect(skillDocument.length, name).toBeGreaterThan(1000);
    }
  });

  it('indexes every skill doc in the Copilot instructions, with its trigger', () => {
    // Progressive disclosure: the index says WHEN to read each doc, so the agent
    // loads only the one that applies rather than all of them up front.
    const index = readFileSync(
      path.resolve(here, '../../.github/copilot-instructions.md'),
      'utf8',
    );
    for (const name of skillNames()) {
      expect(index, name).toContain(`docs/guardrails/${name}.md`);
    }
    expect(index).toContain('when its trigger applies');
  });

  it('tells the fixer that a Stryker directive needs approval, not initiative', () => {
    // The skill is where the sanction flow is explained; the agent must not
    // reach for a disable comment on its own.
    const skill = readFileSync(
      path.join(skillsDirectory, 'crushing-mutants', 'SKILL.md'),
      'utf8',
    );
    expect(skill).toContain('sanctionedSuppressions');
    expect(skill).toContain('You do not add that entry');
  });
});
