/**
 * The consumer template tree is generated by scripts/sync-agents.mjs and
 * committed, and `guardrails init` (piece 4) writes it into a target repo. A
 * file silently dropped from it would produce a consumer whose fixer agents or
 * hooks never got written — which looks like a working install right up until
 * the loop does not fire. These assertions are the contract.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const templates = path.join(import.meta.dirname, '..', 'templates');

const EXPECTED_FILES = [
  'claude/agents/guardrail-fixer.md',
  'claude/agents/guardrail-fixer-thorough.md',
  'claude/settings.hooks.json',
  'codex/agents/guardrail-fixer.toml',
  'codex/agents/guardrail-fixer-thorough.toml',
  'codex/hooks.json',
  'copilot/agents/guardrail-fixer.agent.md',
  'copilot/agents/guardrail-fixer-thorough.agent.md',
  'copilot/hooks/guardrails.json',
  'githooks/pre-commit',
  'githooks/pre-push',
  'workflows/guardrails.yml',
] as const;

describe('consumer templates', () => {
  it.each(EXPECTED_FILES)('ships %s', (relative) => {
    expect(existsSync(path.join(templates, relative))).toBe(true);
  });

  it('carries all five Claude hook events', () => {
    const raw: unknown = JSON.parse(
      readFileSync(
        path.join(templates, 'claude', 'settings.hooks.json'),
        'utf8',
      ),
    );
    expect(raw).toHaveProperty('hooks');
    const { hooks } = raw as { hooks: Record<string, unknown> };
    expect(Object.keys(hooks).sort((a, b) => a.localeCompare(b))).toEqual([
      'PostToolUse',
      'PreToolUse',
      'SessionEnd',
      'SessionStart',
      'Stop',
    ]);
  });

  it('ships all five Codex lifecycle hooks with the Codex dialect', () => {
    const hooks = readFileSync(
      path.join(templates, 'codex', 'hooks.json'),
      'utf8',
    );
    for (const event of [
      'SessionStart',
      'SessionEnd',
      'PreToolUse',
      'PostToolUse',
      'Stop',
    ]) {
      expect(hooks).toContain(`"${event}"`);
    }
    expect(hooks).toContain('--dialect=codex');
    expect(hooks).toContain('apply_patch');
  });

  it('ships valid-looking Codex custom agent definitions', () => {
    const agents = [
      ['guardrail-fixer.toml', 'gpt-5.6-luna', 'low'],
      ['guardrail-fixer-thorough.toml', 'gpt-5.6-terra', 'high'],
    ] as const;
    for (const [agent, model, reasoning] of agents) {
      const content = readFileSync(
        path.join(templates, 'codex', 'agents', agent),
        'utf8',
      );
      expect(content).toContain('name = "guardrail-fixer');
      expect(content).toContain(`model = "${model}"`);
      expect(content).toContain(`model_reasoning_effort = "${reasoning}"`);
      expect(content).toContain('sandbox_mode = "workspace-write"');
      expect(content).toContain("developer_instructions = '''");
    }
  });

  it('ships the self-filtering Claude scope-lock hook', () => {
    const hooks = readFileSync(
      path.join(templates, 'claude', 'settings.hooks.json'),
      'utf8',
    );
    expect(hooks).toContain('"matcher": "Read|Edit|Write"');
    expect(hooks).toContain('scope-check');
  });

  it('resolves guardrails-core through package resolution, never a repo-local path', () => {
    // A template that pointed at this repo's own layout would break in every
    // consumer. The hook commands must resolve the guardrails-core package
    // through Node's module resolution, by name via `-e "import(...)"`, never
    // this repository's own source directory.
    const hooks = readFileSync(
      path.join(templates, 'claude', 'settings.hooks.json'),
      'utf8',
    );
    expect(hooks).toContain("import('guardrails-core/cli')");
    expect(hooks).not.toContain('guardrails-core/src');
  });

  it('ships a pre-commit hook that runs the commit gate', () => {
    const hook = readFileSync(
      path.join(templates, 'githooks', 'pre-commit'),
      'utf8',
    );
    expect(hook).toContain('gate --mode=commit');
  });

  it('ships a pre-commit hook with no prose about THIS repo in it', () => {
    // The hook is copied verbatim into every scaffolded repo, so a sentence
    // true only here ("this repo uses Husky instead, see .husky/pre-commit")
    // lands as a false instruction there: a consumer has no `.husky/`, and
    // following the pointer leads nowhere.
    const hook = readFileSync(
      path.join(templates, 'githooks', 'pre-commit'),
      'utf8',
    );
    expect(hook).not.toContain('.husky');
    expect(hook).not.toContain('This repo');
  });

  it('ships a pre-push hook that runs the branch-scoped gate', () => {
    // The commit rung scopes to staged files, so this is what re-checks the
    // whole branch before anything leaves the machine.
    const hook = readFileSync(
      path.join(templates, 'githooks', 'pre-push'),
      'utf8',
    );
    expect(hook).toContain('gate --mode=push');
  });

  it('ships a pre-push hook with no prose about THIS repo in it', () => {
    const hook = readFileSync(
      path.join(templates, 'githooks', 'pre-push'),
      'utf8',
    );
    expect(hook).not.toContain('.husky');
    expect(hook).not.toContain('This repo');
  });

  it('ships a CI workflow that runs the ci gate plus sanctions-check', () => {
    // `--mode=ci`, not `--mode=commit`: the commit rung scopes to STAGED
    // files, and nothing is staged in a CI checkout, so the old spelling would
    // check an empty set and report clean.
    const workflow = readFileSync(
      path.join(templates, 'workflows', 'guardrails.yml'),
      'utf8',
    );
    expect(workflow).toContain('gate --mode=ci');
    expect(workflow).not.toContain('gate --mode=commit');
    expect(workflow).toContain('sanctions-check');
  });

  it('invokes the CLI by local path, never through npx', () => {
    // npx resolves a BIN NAME and falls through to the registry when nothing
    // local provides it. The bin is named after the package, so a miss lands on
    // this package -- but it can still fetch a different VERSION than `npm ci`
    // installed. CI must run exactly what it installed, so it uses the path
    // form, as this repo's own ci.yml does.
    const workflow = readFileSync(
      path.join(templates, 'workflows', 'guardrails.yml'),
      'utf8',
    );
    expect(workflow).toContain(
      'node ./node_modules/guardrails-core/dist/cli.mjs gate --mode=ci',
    );
    expect(workflow).toContain(
      'node ./node_modules/guardrails-core/dist/cli.mjs sanctions-check',
    );
    // Matched against the `run:` STEPS, not the file text: the template's own
    // comment names `npx guardrails-core` in order to explain why it is not used.
    expect(workflow).not.toMatch(/^ *- run: npx\b/m);
  });

  it('pins CI workflow actions to floating major tags, not a SHA', () => {
    // A pinned SHA written into a consumer's repository would rot silently
    // under THEIR Dependabot policy, unlike this repo's own workflows, which
    // pin because they control their own supply chain.
    const workflow = readFileSync(
      path.join(templates, 'workflows', 'guardrails.yml'),
      'utf8',
    );
    expect(workflow).toContain('actions/checkout@v6');
    expect(workflow).toContain('actions/setup-node@v6');
    expect(workflow).not.toMatch(/uses:\s*\S+@[0-9a-f]{40}/);
  });
});
