/**
 * The consumer template tree is generated by scripts/sync-agents.mjs and
 * committed, and `guardrails init` (piece 4) writes it into a target repo. A
 * file silently dropped from it would produce a consumer whose fixer agents or
 * hooks never got written — which looks like a working install right up until
 * the loop does not fire. These assertions are the contract.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const templates = path.join(import.meta.dirname, '..', 'templates');

const EXPECTED_FILES = [
  'claude/agents/guardrail-fixer.md',
  'claude/agents/guardrail-fixer-thorough.md',
  'claude/settings.hooks.json',
  'copilot/agents/guardrail-fixer.agent.md',
  'copilot/agents/guardrail-fixer-thorough.agent.md',
  'copilot/hooks/guardrails.json',
  'githooks/pre-commit',
  'workflows/guardrails.yml',
] as const;

describe('consumer templates', () => {
  it.each(EXPECTED_FILES)('ships %s', (relative) => {
    expect(existsSync(path.join(templates, relative))).toBe(true);
  });

  it('carries all four Claude hook events', () => {
    const raw: unknown = JSON.parse(
      readFileSync(
        path.join(templates, 'claude', 'settings.hooks.json'),
        'utf8',
      ),
    );
    expect(raw).toHaveProperty('hooks');
    const { hooks } = raw as { hooks: Record<string, unknown> };
    expect(Object.keys(hooks).sort((a, b) => a.localeCompare(b))).toEqual([
      'PostToolUse',
      'SessionEnd',
      'SessionStart',
      'Stop',
    ]);
  });

  it('references guardrails-core through node_modules, never a repo-local path', () => {
    // A template that pointed at this repo's own layout would break in every
    // consumer. The hook commands must resolve through the installed package.
    const hooks = readFileSync(
      path.join(templates, 'claude', 'settings.hooks.json'),
      'utf8',
    );
    expect(hooks).toContain('node_modules/guardrails-core/dist/cli.mjs');
    expect(hooks).not.toContain('guardrails-core/src');
  });

  it('ships a pre-commit hook that runs the commit gate', () => {
    const hook = readFileSync(
      path.join(templates, 'githooks', 'pre-commit'),
      'utf8',
    );
    expect(hook).toContain('gate --mode=commit');
  });

  it('ships a CI workflow that runs the commit gate plus sanctions-check', () => {
    const workflow = readFileSync(
      path.join(templates, 'workflows', 'guardrails.yml'),
      'utf8',
    );
    expect(workflow).toContain('gate --mode=commit');
    expect(workflow).toContain('sanctions-check');
  });

  it('pins CI workflow actions to floating major tags, not a SHA', () => {
    // A pinned SHA written into a consumer's repository would rot silently
    // under THEIR Dependabot policy, unlike this repo's own workflows, which
    // pin because they control their own supply chain.
    const workflow = readFileSync(
      path.join(templates, 'workflows', 'guardrails.yml'),
      'utf8',
    );
    expect(workflow).toContain('actions/checkout@v6');
    expect(workflow).toContain('actions/setup-node@v6');
    expect(workflow).not.toMatch(/uses:\s*\S+@[0-9a-f]{40}/);
  });
});
