#!/usr/bin/env node
// Sync the fixer agents AND skills from the plugin (the single source of truth)
// into .claude/, so this repo's dogfooded loop uses the same definitions with
// no dual maintenance. Runs as part of `npm run build` (and therefore `prepare`,
// pre-push, and CI). `.claude/agents/` is generated and gitignored — never edit
// it directly; edit guardrails-plugin/agents/ and rebuild.
//
// Also emits Copilot-format fixers to .github/agents/*.agent.md. Unlike
// .claude/agents/, that directory is COMMITTED — the Copilot cloud agent reads
// it from the default branch — so a CI drift-guard (`git diff --exit-code --
// .github/agents`) keeps the committed output in sync with the source.
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const from = path.join(root, 'guardrails-plugin', 'agents');
const to = path.join(root, '.claude', 'agents');
const githubAgents = path.join(root, '.github', 'agents');

// Clear the destination first so a source file that was renamed or deleted
// can't leave a stale generated copy behind (`.claude/agents/` is gitignored, so
// a leftover would persist silently — the exact drift this script prevents).
rmSync(to, { recursive: true, force: true });
mkdirSync(to, { recursive: true });
const agents = readdirSync(from).filter((file) => file.endsWith('.md'));
for (const file of agents) {
  copyFileSync(path.join(from, file), path.join(to, file));
}
console.log(
  `synced ${agents.length} agent(s): guardrails-plugin/agents → .claude/agents`,
);

// Skills ship with the plugin too, and the dogfooded loop should see the same
// ones a consumer gets. Copied wholesale (a skill is a directory: SKILL.md plus
// any references), same clear-first rule as the agents above so a renamed or
// deleted skill cannot leave a stale generated copy behind.
const skillsFrom = path.join(root, 'guardrails-plugin', 'skills');
const skillsTo = path.join(root, '.claude', 'skills');
rmSync(skillsTo, { recursive: true, force: true });
let skillCount = 0;
if (existsSync(skillsFrom)) {
  mkdirSync(skillsTo, { recursive: true });
  for (const entry of readdirSync(skillsFrom, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    cpSync(path.join(skillsFrom, entry.name), path.join(skillsTo, entry.name), {
      recursive: true,
    });
    skillCount += 1;
  }
}
console.log(
  `synced ${skillCount} skill(s): guardrails-plugin/skills → .claude/skills`,
);

// Copilot has no skill mechanism, so the same skills are ALSO emitted as plain
// docs plus an index in .github/copilot-instructions.md ("progressive
// disclosure": the index says when to read each doc; the agent loads only the
// one it needs). Unlike .claude/skills/, these are COMMITTED and CI
// drift-guards them, because Copilot's cloud agent reads from the default
// branch. Single source of truth stays guardrails-plugin/skills/.
const skillDocs = path.join(root, 'docs', 'guardrails');
const copilotInstructions = path.join(
  root,
  '.github',
  'copilot-instructions.md',
);

// guardrails-core's `guidance.ts` points violations at these same docs, but a
// CONSUMER repo only installs the npm package (`files: ["dist", "guidance"]`),
// never docs/guardrails at the repo root. So the same skill docs are ALSO
// emitted into guardrails-core/guidance/, which ships with the package and
// resolves via node_modules in any consumer. Committed and CI drift-guarded
// alongside docs/guardrails, for the same reason.
const packageGuidance = path.join(root, 'guardrails-core', 'guidance');

function parseSkill(name) {
  const source = readFileSync(path.join(skillsFrom, name, 'SKILL.md'), 'utf8');
  const parts = source.split(/^---$/m);
  const fm = parts[1] ?? '';
  // Same all-leading-newlines strip as toCopilotAgent, for the same reason: a
  // spurious blank line would be collapsed by prettier at commit and make the
  // raw build output disagree with the committed file on every CI run.
  const body = parts.slice(2).join('---').replace(/^\n+/, '').trimEnd();
  return { name, description: frontmatterField(fm, 'description'), body };
}

rmSync(skillDocs, { recursive: true, force: true });
rmSync(packageGuidance, { recursive: true, force: true });
const skillList = existsSync(skillsFrom)
  ? readdirSync(skillsFrom, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => parseSkill(entry.name))
  : [];
if (skillList.length > 0) {
  mkdirSync(skillDocs, { recursive: true });
  mkdirSync(packageGuidance, { recursive: true });
  for (const skill of skillList) {
    const content = [
      `<!-- Generated by scripts/sync-agents.mjs from guardrails-plugin/skills/${skill.name}/SKILL.md — do not edit. -->`,
      '',
      skill.body,
      '',
    ].join('\n');
    writeFileSync(path.join(skillDocs, `${skill.name}.md`), content);
    writeFileSync(path.join(packageGuidance, `${skill.name}.md`), content);
  }

  // guidance/ ships only each skill's BODY (parseSkill strips the
  // frontmatter before writing it above), so a consumer's installed
  // docs/guardrails/*.md land with no trigger text of their own -- `init`
  // has nothing to build a Copilot index from. This index carries exactly
  // the piece parseSkill stripped: name -> description, so templates.ts can
  // rebuild both the .claude/skills/*/SKILL.md frontmatter and the
  // .github/copilot-instructions.md index at install time. Deterministic
  // (sorted keys, two-space indent, trailing newline) for the same reason
  // manifest.ts's serializeManifest is: the committed file stays out of
  // every diff and the CI drift-guard can work on it.
  const index = {};
  for (const skill of [...skillList].sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    index[skill.name] = skill.description;
  }
  writeFileSync(
    path.join(packageGuidance, 'index.json'),
    `${JSON.stringify(index, undefined, 2)}\n`,
  );
}

// Replace only the marked block, so hand-written Copilot instructions around it
// survive a rebuild.
const START = '<!-- guardrails:skills:start -->';
const END = '<!-- guardrails:skills:end -->';
const index = [
  START,
  '',
  '## Guardrails reference docs',
  '',
  'Read the linked doc **when its trigger applies** — not up front.',
  '',
  ...skillList.map(
    (skill) =>
      `- [\`${skill.name}\`](../docs/guardrails/${skill.name}.md) — ${skill.description}`,
  ),
  '',
  END,
].join('\n');
const existing = existsSync(copilotInstructions)
  ? readFileSync(copilotInstructions, 'utf8')
  : `# Copilot instructions\n\n${START}\n${END}\n`;
const startAt = existing.indexOf(START);
const endAt = existing.indexOf(END);
const merged =
  startAt === -1 || endAt === -1
    ? `${existing.trimEnd()}\n\n${index}\n`
    : `${existing.slice(0, startAt)}${index}${existing.slice(endAt + END.length)}`;
writeFileSync(copilotInstructions, merged);
console.log(
  `synced ${skillList.length} skill doc(s): guardrails-plugin/skills → docs/guardrails + guardrails-core/guidance + .github/copilot-instructions.md`,
);

// Copilot fixer tool allowlist (Copilot tool names, NOT Claude's). Read+edit
// family only; `bash` and `agent`/`task` are withheld so the fixer can't shell
// out or fan out (the latter reinforced by `agents: []`).
const COPILOT_TOOLS = [
  'view',
  'edit',
  'create',
  'apply_patch',
  'str_replace_editor',
];

// Map the CC model tier keyword → a Copilot model id from guardrails.config.json.
// These knobs default UNSET, so the generated `.agent.md` omits `model:`. That is
// deliberate and safe (see plan.md's "Copilot fixer tier-ladder" note): on VS Code
// an unset model inherits the picker/session model — the THOROUGH fixer is never
// silently downgraded — while the Copilot CLI ignores this field entirely and the
// cloud agent uses "Auto". GitHub publishes no enumerated id list (values are
// account-/surface-specific and drift), so hardcoding a default would be fragile.
// A user who wants VS-Code tier-pinning sets copilotFastModel/copilotThoroughModel.
const cfg = (() => {
  try {
    return JSON.parse(
      readFileSync(path.join(root, 'guardrails.config.json'), 'utf8'),
    );
  } catch {
    return {};
  }
})();
const MODEL_FOR = {
  haiku: cfg.copilotFastModel,
  sonnet: cfg.copilotThoroughModel,
};

function frontmatterField(fm, key) {
  const m = fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'));
  return m ? m[1].trim() : undefined;
}

function toCopilotAgent(source) {
  const parts = source.split(/^---$/m);
  // parts[0] = '' , parts[1] = frontmatter , parts.slice(2) = body
  const fm = parts[1];
  // Strip ALL leading newlines (not just one): the source has a blank line
  // after its closing frontmatter `---`, and `lines.push('---', '', body, '')`
  // below already inserts the single separator blank line. Stripping only one
  // newline here would leave a second, spurious blank line that prettier (run
  // by lint-staged at commit) collapses away — making the raw `npm run build`
  // output permanently disagree with the committed, prettier-clean file and
  // fail the CI drift-guard on every run.
  const body = parts.slice(2).join('---').replace(/^\n+/, '');
  const name = frontmatterField(fm, 'name');
  const description = frontmatterField(fm, 'description');
  const model = MODEL_FOR[frontmatterField(fm, 'model')];
  const lines = ['---', `name: ${name}`, `description: ${description}`];
  lines.push(`tools: [${COPILOT_TOOLS.join(', ')}]`);
  lines.push('agents: []');
  if (model) lines.push(`model: ${model}`);
  lines.push('---', '', body.trimEnd(), '');
  return lines.join('\n');
}

rmSync(githubAgents, { recursive: true, force: true });
mkdirSync(githubAgents, { recursive: true });
for (const file of agents) {
  const source = readFileSync(path.join(from, file), 'utf8');
  const target = file.replace(/\.md$/, '.agent.md');
  writeFileSync(path.join(githubAgents, target), toCopilotAgent(source));
}
console.log(
  `synced ${agents.length} agent(s): guardrails-plugin/agents → .github/agents (.agent.md)`,
);

// Consumer-facing templates, shipped in the npm tarball (`files`) and written
// into a target repo by `guardrails init` (piece 4). The sources are all
// consumer-generic — they reference `${CLAUDE_PROJECT_DIR}` / `./node_modules`,
// never a path specific to this repo. Committed and CI drift-guarded, like
// .github/agents.
//
// For the agents, the Claude hook block and the Copilot hooks, the source IS
// this repo's own live wiring: what we dogfood is exactly what we ship, so the
// two cannot drift. `.githooks/pre-commit` is the exception and should not be
// read as dogfooded — this repo's `core.hooksPath` is `.husky/_`, so that file
// never executes here; `.husky/pre-commit` runs the same `gate --mode=commit`
// line instead. It is authored here and shipped, not proven here.
const templates = path.join(root, 'guardrails-core', 'templates');
rmSync(templates, { recursive: true, force: true });

const claudeAgents = path.join(templates, 'claude', 'agents');
mkdirSync(claudeAgents, { recursive: true });
for (const file of agents) {
  copyFileSync(path.join(from, file), path.join(claudeAgents, file));
}

const copilotAgents = path.join(templates, 'copilot', 'agents');
mkdirSync(copilotAgents, { recursive: true });
for (const file of agents) {
  const target = file.replace(/\.md$/, '.agent.md');
  // toCopilotAgent takes the file CONTENTS, not a path -- match the existing
  // .github/agents emitter above, which reads the file first.
  writeFileSync(
    path.join(copilotAgents, target),
    toCopilotAgent(readFileSync(path.join(from, file), 'utf8')),
  );
}

// Only the `hooks` block: a consumer's .claude/settings.json is THEIR file, and
// `init` merges this in rather than replacing it.
const claudeSettings = JSON.parse(
  readFileSync(path.join(root, '.claude', 'settings.json'), 'utf8'),
);
mkdirSync(path.join(templates, 'claude'), { recursive: true });
writeFileSync(
  path.join(templates, 'claude', 'settings.hooks.json'),
  `${JSON.stringify({ hooks: claudeSettings.hooks }, undefined, 2)}\n`,
);

const copilotHooks = path.join(templates, 'copilot', 'hooks');
mkdirSync(copilotHooks, { recursive: true });
copyFileSync(
  path.join(root, '.github', 'hooks', 'guardrails.json'),
  path.join(copilotHooks, 'guardrails.json'),
);

const gitHooks = path.join(templates, 'githooks');
mkdirSync(gitHooks, { recursive: true });
copyFileSync(
  path.join(root, '.githooks', 'pre-commit'),
  path.join(gitHooks, 'pre-commit'),
);

// Consumer CI workflow (spec §8.1). Unlike the wiring files above, this one
// has no "this repo's own live wiring" source to copy from: this repo's own
// `.github/workflows/ci.yml` pins commit SHAs and does far more than a
// consumer needs (lint, typecheck, build, coverage, tarball smoke). So the
// consumer-generic version is authored directly in the plugin, not derived.
const workflowsFrom = path.join(
  root,
  'guardrails-plugin',
  'templates',
  'workflows',
);
const workflowsTo = path.join(templates, 'workflows');
mkdirSync(workflowsTo, { recursive: true });
copyFileSync(
  path.join(workflowsFrom, 'guardrails.yml'),
  path.join(workflowsTo, 'guardrails.yml'),
);

console.log(`synced consumer templates → guardrails-core/templates`);
